name: igdb
description: Client library to access the IGDB (Internet Game Database) API
version: 0.0.1
homepage: https://github.com/Erly/igdb
author: erlantz <erlantz8@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.0

dev_dependencies:
  test: ^0.12.0
